// Barrel export for all OS icon components mapped to the Fluent icon system
export { OsIcon } from "./OsIcon";
export type { IconSize, IconBadge } from "./OsIconWrapper";

export {
  FolderIcon,
  FolderOpenIcon,
  FileIcon,
  DriveIcon,
  TrashIcon,
  TerminalIcon,
  SettingsIcon,
  UserIcon,
  InfoIcon,
  ShieldIcon,
  MailIcon,
  LogIcon,
  TrophyIcon,
  SkillsIcon,
  PhotoIcon,
  GameIcon,
  DiskIcon,
  PawIcon,
  WindowsLogoIcon,
  SearchIcon,
  VolumeIcon,
  WifiIcon,
  BatteryIcon,
  ClockIcon,
  NotifIcon,
  PowerIcon,
  WidgetsIcon,
  BluetoothIcon,
  NightLightIcon,
  RotationLockIcon,
  HotspotIcon,
  NearbyShareIcon,
  CastIcon,
  AccessibilityIcon,
  CloseIcon,
  MinimizeIcon,
  MaximizeIcon,
  RestoreIcon,
  RefreshIcon,
  NewIcon,
  SortIcon,
  ViewIcon,
  PersonalizeIcon,
  DisplayIcon,
  PropertiesIcon,
  ChevronRightIcon,
  PinIcon,
  UnpinIcon,
  CheckIcon,
  LinkIcon,
  RocketIcon,
  LockIcon,
  UnlockIcon,
  TargetIcon,
  CoinsIcon,
  FrownIcon,
  CloverIcon,
  KeyIcon,
} from "./OsIcon";

